Repository Swahilipot-Hub-Developers/members-management, pull requests merged in 2023-11, with the labels that each got.

#12 Project changes
  backend/backend/__pycache__/urls.cpython-311.pyc
  backend/membersmgmt/__pycache__/views.cpython-311.pyc
  frontend/src/components/analyticcard.js
  frontend/src/components/members-list.js
  frontend/src/pages/index.js
  frontend/src/pages/members.js
  frontend/src/pages/sessions/register-member.js
Labels: bug

#13 Backend Changes
  backend/backend/__pycache__/settings.cpython-310.pyc
  backend/backend/__pycache__/urls.cpython-310.pyc
  backend/backend/settings.py
  backend/membersmgmt/__pycache__/serializers.cpython-310.pyc
  backend/membersmgmt/__pycache__/urls.cpython-310.pyc
  backend/membersmgmt/__pycache__/views.cpython-310.pyc
  backend/membersmgmt/views.py
  frontend/src/components/members-list.js
  frontend/src/pages/sessions/register-member.js
Labels: enhancement

#16 Documentation changes
  README.md
Labels: documentation

#15 Form checking and functionality
  backend/backend/__pycache__/settings.cpython-311.pyc
  backend/backend/__pycache__/urls.cpython-311.pyc
  backend/backend/urls.py
  backend/db.sqlite3
  backend/membersmgmt/__pycache__/models.cpython-311.pyc
  backend/membersmgmt/__pycache__/urls.cpython-311.pyc
  backend/membersmgmt/__pycache__/views.cpython-311.pyc
  backend/membersmgmt/migrations/0001_initial.py
  backend/membersmgmt/migrations/__pycache__/0001_initial.cpython-310.pyc
  backend/membersmgmt/migrations/__pycache__/0001_initial.cpython-311.pyc
  backend/membersmgmt/migrations/__pycache__/__init__.cpython-310.pyc
  backend/membersmgmt/migrations/__pycache__/__init__.cpython-311.pyc
  backend/membersmgmt/models.py
  backend/membersmgmt/urls.py
  backend/membersmgmt/views.py
  frontend/src/components/analyticcard.js
  frontend/src/components/members-list.js
  frontend/src/pages/analytics.js
  frontend/src/pages/index.js
  frontend/src/pages/sessions/register-member.js
Labels: bug, enhancement

#19 More changes to the backend
  backend/db.sqlite3
  backend/membersmgmt/__pycache__/admin.cpython-311.pyc
  backend/membersmgmt/__pycache__/models.cpython-311.pyc
  backend/membersmgmt/__pycache__/serializers.cpython-311.pyc
  backend/membersmgmt/__pycache__/urls.cpython-311.pyc
  backend/membersmgmt/__pycache__/views.cpython-311.pyc
  backend/membersmgmt/admin.py
  backend/membersmgmt/migrations/0002_delete_admin.py
  backend/membersmgmt/migrations/0003_adminprofile.py
  backend/membersmgmt/migrations/0004_alter_member_gender.py
  backend/membersmgmt/migrations/__pycache__/0002_delete_admin.cpython-311.pyc
  backend/membersmgmt/migrations/__pycache__/0003_adminprofile.cpython-311.pyc
  backend/membersmgmt/migrations/__pycache__/0004_alter_member_gender.cpython-311.pyc
  backend/membersmgmt/models.py
  backend/membersmgmt/serializers.py
  backend/membersmgmt/urls.py
  backend/membersmgmt/views.py
  frontend/src/components/members-list.js
Labels: bug, duplicate, enhancement, help wanted

#41 Changes to the Project
  README.md
  backend/backend/settings.py
  backend/membersmgmt/urls.py
  backend/membersmgmt/views.py
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/edit-section.js
  frontend/src/components/members-list.js
  frontend/src/layout/NavBar.js
  frontend/src/pages/sessions/register-member.js
Labels: bug, documentation, enhancement, testing
